package cn.magicvector.common.application.util;

import cn.magicvector.common.basic.util.GenericsUtils;

import java.lang.reflect.Method;

/**
 * Utils for java objects.
 */
public class ObjectUtil {


    /**
     * Get the target method definition of the given instance.
     *
     * @param targetInstance the given instance
     * @param args the
     * @param methodName
     * @param parameterTypes
     * @return
     */
    public static Method getTargetMethod(Object targetInstance, Object [] args, String methodName, Class[] parameterTypes){
        Method result = null;
        try {
            // get the target method
            result = targetInstance.getClass().getMethod(methodName, parameterTypes);
            // if the target method is a bridge method which is generated by JVM in the case of Generic Type.
            if(result.isBridge()){
                for(int i = 0; i < args.length; i++){
                    //
                    Class runtimeGenericClazz = GenericsUtils.getSuperClassGenricType(targetInstance.getClass());
                    // find the generic type
                    if( args[i].getClass().isAssignableFrom(runtimeGenericClazz) ){
                        parameterTypes[i] = runtimeGenericClazz;
                    }
                }
                //get actual parameter types
                result = targetInstance.getClass().getMethod(methodName, parameterTypes);
            }
        } catch (SecurityException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        }
        return result;
    }


    /**
     * Get the target method definition of the given instance.
     *
     * @param targetInstance the given instance
     * @param args the
     * @param methodName
     * @param parameterTypes
     * @return
     */
    public static Method getInterfaceMethod(Object targetInstance, Object [] args, String methodName, Class[] parameterTypes){
        Method result = null;
        try {
            // get the target method
            if( targetInstance.getClass().getInterfaces() == null || targetInstance.getClass().getInterfaces().length == 0 ){
                return null;
            }
            Class interfaceClass = targetInstance.getClass().getInterfaces()[0];
            result = interfaceClass.getMethod(methodName, parameterTypes);
            // if the target method is a bridge method which is generated by JVM in the case of Generic Type.
            if(result.isBridge()){
                for(int i = 0; i < args.length; i++){
                    //
                    Class runtimeGenericClazz = GenericsUtils.getSuperClassGenricType(targetInstance.getClass());
                    // find the generic type
                    if( args[i].getClass().isAssignableFrom(runtimeGenericClazz) ){
                        parameterTypes[i] = runtimeGenericClazz;
                    }
                }
                //get actual parameter types
                result = targetInstance.getClass().getMethod(methodName, parameterTypes);
            }
        } catch (SecurityException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        }
        return result;
    }

}
