package cn.magicvector.common.application.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.Valid;

@ApiModel(description = "The basic contract content of client's requests.")
@Data
public class Request<T> {

	/**
	 * request's id
	 */
	@ApiModelProperty(notes = "Request's id generated by client")
	private String requestId;


	@ApiModelProperty(notes="User's access token",example="xxxxxxxxxxxxxx", allowEmptyValue = true)
	private String token;

	/**
	 * trace's id
	 */
	@ApiModelProperty(notes = "Request's trace id generated by client")
	private String traceId;

	/**
	 * Circle's id
	 */
	@ApiModelProperty(notes = "Tenant id, used for SaaS.")
	private String tenantId;

	/**
	 * Request's source
	 */
	@ApiModelProperty(notes = "Identify where is the request from, app, website, or micro-app.")
	private String source;

	/**
	 * Request's parameter.
	 */
	@Valid
	@ApiModelProperty(notes = "The request's parameter.")
	private T parameter;


}
